CREATE TABLE team_members (
    team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    invite_date TIMESTAMPTZ DEFAULT now() NOT NULL,
    accepted BOOLEAN NOT NULL DEFAULT FALSE
);
